### ISSUE TITLE
Title does not support emojis

### ISSUE THREAD

**Issue by patschi** [Rongronggg9/RSS-to-Telegram-Bot#162]
**Describe the bug**
When using RSS with emojis in title, it does not correctly post the same emoji as the title in the Telegram message. It looks like:
```
๐ŸŒŠ๐Ÿ„ Amoogust Update 2022 - The Nightly Build Switch Update (Revision B) | Changes
```

See:
![image](https://user-images.githubusercontent.com/2029878/190543419-74098c17-9621-4120-a681-ade2a0553364.png)

**To Reproduce**
1. Let the feed post it as Telegram message
2. Use `/test https://news.mailcow.email/index.xml`

**Expected behavior**
See emoji.

**Important log**
n/a

**Comment by Rongronggg9** [comment]
Hmmm, not reproducible...
![](https://user-images.githubusercontent.com/15956627/190545613-3c5e11ef-8430-40ed-a300-25c7b5a08d14.png)

`/version` of your bot?

**Comment by patschi** [comment]
I've installed the bot just a few minutes ago, so it's the latest build on docker hub:
```
v2.2.1-@master
build@202202T10:56:13+00:00
```

Maybe it's related to any customized default settings I use? I can strangely reproduce it every time

![image](https://user-images.githubusercontent.com/2029878/190545919-8c9741d9-b7fc-4ec7-a583-d24686cbcfb5.png)

**Comment by Rongronggg9** [comment]
Try `dev`? I am too busy to make a new release so `master` is now considered not stable.

**Comment by patschi** [comment]
Switching to image:
```
    image: rongronggg9/rss-to-telegram:dev@sha256:479129b418e0a2d23cd4685d954afcb5bdfe6a5ee410811ca3145a6cb1a8c1b6
```

Causes the bot to crash during startup:

```text
2022-09-16-02:56:24:INFO:RSStT.env - Config folder: /app/config
2022-09-16-02:56:24:DEBUG:RSStT.env - DEBUG mode enabled
2022-09-16-02:56:26:INFO:RSStT - Exiting gracefully...
2022-09-16-02:56:26:ERROR:asyncio - Exception in callback functools.partial(<function AsyncIOScheduler.shutdown at 0x7f60a975a290>, <apscheduler.schedulers.asyncio.AsyncIOScheduler object at 0x7f60aa9ef160>, wait=False)
handle: <Handle functools.partial(<function AsyncIOScheduler.shutdown at 0x7f60a975a290>, <apscheduler.schedulers.asyncio.AsyncIOScheduler object at 0x7f60aa9ef160>, wait=False)>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 61, in uvloop.loop.Handle._run
  File "/opt/venv/lib/python3.10/site-packages/apscheduler/schedulers/asyncio.py", line 49, in shutdown
    super(AsyncIOScheduler, self).shutdown(wait)
  File "/opt/venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 189, in shutdown
    raise SchedulerNotRunningError
apscheduler.schedulers.SchedulerNotRunningError: Scheduler is not running
```

Adding `NO_UVLOOP=1` to env doesn't change anything either: 
(not too familiar with the code base, so seems to be something different)

```
2022-09-16-02:58:33:INFO:RSStT.env - Config folder: /app/config
2022-09-16-02:58:33:DEBUG:RSStT.env - DEBUG mode enabled
2022-09-16-02:58:33:DEBUG:asyncio - Using selector: EpollSelector
2022-09-16-02:58:34:INFO:RSStT - Exiting gracefully...
2022-09-16-02:58:34:ERROR:asyncio - Exception in callback AsyncIOScheduler.shutdown(<apscheduler....x7fc01d023130>, wait=False)() at /opt/venv/lib/python3.10/site-packages/apscheduler/schedulers/asyncio.py:47
handle: <Handle AsyncIOScheduler.shutdown(<apscheduler....x7fc01d023130>, wait=False)() at /opt/venv/lib/python3.10/site-packages/apscheduler/schedulers/asyncio.py:47>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/venv/lib/python3.10/site-packages/apscheduler/schedulers/asyncio.py", line 49, in shutdown
    super(AsyncIOScheduler, self).shutdown(wait)
  File "/opt/venv/lib/python3.10/site-packages/apscheduler/schedulers/base.py", line 189, in shutdown
    raise SchedulerNotRunningError
apscheduler.schedulers.SchedulerNotRunningError: Scheduler is not running
```

**Comment by Rongronggg9** [comment]
OK, this is a bug. I will fix it!

**Comment by patschi** [comment]
Wow! That was insanely quick! Very, very appreciated!

Docker Image has been pushed, switched now to:
```
    image: rongronggg9/rss-to-telegram:dev@sha256:243a338e43eeffe7ea1db0d9fa5103d1377d4265c6e26781914c64e7362cfb49
```

Testing now again - the issue is fixed and emoji is shown as expected. Seems to be indeed related to the current master build.
![image](https://user-images.githubusercontent.com/2029878/190548777-4ff5f6b8-2efc-4f3c-ade4-2abce835248e.png)
