### ISSUE TITLE
Problem when installing on k3s

### ISSUE THREAD

**Issue by Haasie** [Rongronggg9/RSS-to-Telegram-Bot#183]
Hello,

I run your nice application for quite a while now. Past week inwas migrating my cluster and i keep getting this error

```2022-10-06-16:58:29:INFO:RSStT.env - Config folder: /app/config
2022-10-06-16:58:31:INFO:RSStT - API_ID and/or API_HASH not set, use sample APIs instead. API_ID_PUBLISHED_FLOOD_ERROR may occur.
Traceback (most recent call last):
  File "/app/telegramRSSbot.py", line 1, in <module>
    import src
  File "/app/src/__init__.py", line 46, in <module>
    bot = TelegramClient(path.join(env.config_folder_path, 'bot'),
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.FloodWaitError: A wait of 73382 seconds is required (caused by ImportBotAuthorizationRequest)```

Can please give me some guidance?
Kind regards

**Comment by Rongronggg9** [comment]
Hmm, IDK what k3s is. Maybe Telegram has blocklisted its IP(s)?

**Comment by Rongronggg9** [comment]
Some additional hints:
Did you migrate your `config/bot.session` as well? Delete it and retry.
Do you have your own API ID&Hash? Register one if none and configure it.

**Comment by Haasie** [comment]
> Hmm, maybe Telegram has blocklisted your IP? AFAIK, Telegram returns a long flood wait BEFORE OR DURING login only if:
> 
> 1. Your DC is experiencing a service downgraded.
> 2. Your IP is blocked.

Thanks for your reply. I set up my own "api" to talk to, made another both with different api etc. also removed all old files so fresh install. 

this are the current logs from it 
```
2022-10-07-11:06:50:INFO:RSStT.env - Config folder: /app/config
Traceback (most recent call last):
  File "/app/telegramRSSbot.py", line 1, in <module>
    import src
  File "/app/src/__init__.py", line 46, in <module>
    bot = TelegramClient(path.join(env.config_folder_path, 'bot'),
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.AccessTokenInvalidError: The provided token is not valid (caused by ImportBotAuthorizationRequest)
joerihaas@MacBook-Pro-van-Joeri:~/GitHub/k3s-node|main ⇒  kubectl logs rss-to-telegram-5794486b75-c8t6q  -n default
2022-10-07-11:06:50:INFO:RSStT.env - Config folder: /app/config
Traceback (most recent call last):
  File "/app/telegramRSSbot.py", line 1, in <module>
    import src
  File "/app/src/__init__.py", line 46, in <module>
    bot = TelegramClient(path.join(env.config_folder_path, 'bot'),
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 133, in start
    else self.loop.run_until_complete(coro)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 182, in _start
    await self.sign_in(bot_token=bot_token)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/auth.py", line 368, in sign_in
    result = await self(request)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/opt/venv/lib/python3.10/site-packages/telethon/client/users.py", line 84, in _call
    result = await future
telethon.errors.rpcerrorlist.AccessTokenInvalidError: The provided token is not valid (caused by ImportBotAuthorizationRequest
``` 

This are the settings i use in my secret file: 
```
apiVersion: v1
kind: Secret
metadata:
    name: rss-to-telegram
    namespace: default
stringData:
    TOKEN: "123456789"
    MANAGER: 987654321:AAFuRk5ucWJicP3wewr43wWW3uWk4TiL9y408
    API_ID: "11176543"
    API_HASH: fdc7e10ac2346727824as5402e2a28a555d```

**used dummy date**

**Comment by Rongronggg9** [comment]
You reversed `TOKEN` and `MANAGER` 😂

**Comment by Haasie** [comment]
Ohhhhh myyyyyyy. After a lot of tries it finally works!! Thank you for your help and sorry for my stupidity.
