### ISSUE TITLE
/test 出现 403 forbidden

### ISSUE THREAD

**Issue by CRH6F-A-0464** [Rongronggg9/RSS-to-Telegram-Bot#2]
```
Something went wrong while sending this message. Please check:  
  
Traceback (most recent call last):  
File "/app/message.py", line 18, in send  
send_message(chatid, xml, feed_title, url, context)  
File "/app/message.py", line 30, in send_message  
video = validate_medium(getVideo.findall(xml)[0], 20971520)  
File "/app/message.py", line 78, in validate_medium  
size, width, height = get_pic_info(url)  
File "/app/message.py", line 54, in get_pic_info  
urlopen = request.urlopen(url)  
File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen  
return opener.open(url, data, timeout)  
File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open  
response = meth(req, response)  
File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response  
'http', request, response, code, msg, hdrs)  
File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error  
return self._call_chain(*args)  
File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain  
result = func(*args)  
File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default  
raise HTTPError(req.full_url, code, msg, hdrs, fp)  
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by CRH6F-A-0464** [comment]
使用的rss源为自建rsshub实例.

**Comment by Rongronggg9** [comment]
请问该微博是否含有视频？
这是一个已知问题，由视频链接中的转义未消除引起，正在修复中。

**Comment by Rongronggg9** [comment]
Fixed. e711a1c
