### ISSUE TITLE
Add Referer Header when fecthing image medium

### ISSUE THREAD

**Issue by JingMatrix** [Rongronggg9/RSS-to-Telegram-Bot#305]
**Describe the bug**

Some images hosting services such as `https://b-1254719278.cos.accelerate.myqcloud.com/wp-content/uploads` will refuse to load images if no valid `Referer` header is present in the request.

**To Reproduce**
An examplar feed is: https://bedtimepoem.com/feed/atom
To see the issue, the command
```sh
curl -I 'https://b-1254719278.cos.accelerate.myqcloud.com/wp-content/uploads/2023/07/WechatIMG19-1024x1024.jpg'
```
returns 403.
But the command
```sh
curl -I 'https://b-1254719278.cos.accelerate.myqcloud.com/wp-content/uploads/2023/07/WechatIMG19-1024x1024.jpg' \
  -H 'Referer: https://bedtimepoem.com/archives/17372'
```
returns 200 correctly.

**Expected behavior**
rsstt should add the Referer header so that images can be fetched reliably.

**Important log**
```
Traceback (most recent call last):
  File "/home/jing/.local/python/lib/python3.11/site-packages/rsstt/web.py", line 457, in get_medium_info
    raise ValueError(f'status code is not 200, but {r.status}')
ValueError: status code is not 200, but 403
2023-07-21-16:21:12:DEBUG:RSStT.web - Medium fetch failed: https://b-1254719278.cos.accelerate.myqcloud.com/wp-content/uploads/2023/07/WechatIMG19-1024x1024.jpg
Traceback (most recent call last):
  File "/home/jing/.local/python/lib/python3.11/site-packages/asyncstdlib/_lrucache.py", line 407, in __call__
    result = self.__cache[key]
             ~~~~~~~~~~~~^^^^^
KeyError: 'https://b-1254719278.cos.accelerate.myqcloud.com/wp-content/uploads/2023/07/WechatIMG19-1024x1024.jpg'
```

**Comment by Rongronggg9** [comment]
Sounds reasonable. However, I am pretty occupied these days so PR is welcomed.

**Comment by JingMatrix** [comment]
Hi! Do you have related development documents? I didn't find them yet.

Most importantly, how do you set up a test environment locally?

**Comment by Rongronggg9** [comment]
Hmm, it seems that only RSStT fetching images with proper referer is not sufficient. RSStT relies on Telegram DC to finally fetch and send images. That RSStT itself succeeds in fetching images does not mean the success of Telegram DC, while it is the latter that is the key to sending images.
To fix the issue, https://github.com/Rongronggg9/rsstt-img-relay needs to accept custom HTTP headers first. Afterward, RSStT can benefit from it.

**Comment by JingMatrix** [comment]
Hello, @Rongronggg9 , do you have any news on this issue?
If possible, please share your thought on how to implement it via image relay.
