### ISSUE TITLE
部署在vultr docker出错

### ISSUE THREAD

**Issue by benzking** [Rongronggg9/RSS-to-Telegram-Bot#5]
根据readme部署完，机器人没有反应，日志如下，麻烦帮忙看看是什么问题，如果大佬方便请 加电报@modrichGo

2021-02-18 14:36:37,172 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 425, in process_update

    handler.handle_update(update, self, check, context)

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 145, in handle_update

    return self.callback(update, context)

  File "telegramRSSbot.py", line 145, in cmd_help

    is_manager(update)

  File "telegramRSSbot.py", line 41, in is_manager

    name = chat.first_name + ' ' + chat.last_name

TypeError: can only concatenate str (not "NoneType") to str

2021-02-18 14:36:40,833 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 425, in process_update

    handler.handle_update(update, self, check, context)

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 145, in handle_update

    return self.callback(update, context)

  File "telegramRSSbot.py", line 145, in cmd_help

    is_manager(update)

  File "telegramRSSbot.py", line 41, in is_manager

    name = chat.first_name + ' ' + chat.last_name

TypeError: can only concatenate str (not "NoneType") to str

2021-02-18 14:36:53,525 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 425, in process_update

    handler.handle_update(update, self, check, context)

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 145, in handle_update

    return self.callback(update, context)

  File "telegramRSSbot.py", line 145, in cmd_help

    is_manager(update)

  File "telegramRSSbot.py", line 41, in is_manager

    name = chat.first_name + ' ' + chat.last_name

TypeError: can only concatenate str (not "NoneType") to str

2021-02-18 14:37:05,205 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.

Traceback (most recent call last):

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/dispatcher.py", line 425, in process_update

    handler.handle_update(update, self, check, context)

  File "/usr/local/lib/python3.7/site-packages/telegram/ext/handler.py", line 145, in handle_update

    return self.callback(update, context)

  File "telegramRSSbot.py", line 104, in cmd_rss_add

    is_manager(update)

  File "telegramRSSbot.py", line 41, in is_manager

    name = chat.first_name + ' ' + chat.last_name

TypeError: can only concatenate str (not "NoneType") to str

**Comment by Rongronggg9** [comment]
@benzking Fixed. 4d86acb

请留意 docker 需要手动更新。

**Comment by Rongronggg9** [comment]
@benzking name = chat.first_name + ' ' + chat.last_name 
 
TypeError: can only concatenate str (not "NoneType") to str


Fixed. 4d86acb

请留意 docker 需要手动更新。
